spring:
  application:
    name: user-management-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/publisher_subscriber?useSSL=false
    username: chamila
    password: Password@123
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update

server:
  port: 8889

eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/